services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: time_management_db
      # PostgreSQL memory optimization parameters
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_SHARED_BUFFERS: "1GB" 
      POSTGRES_WORK_MEM: "32MB"
      POSTGRES_MAINTENANCE_WORK_MEM: "256MB"
      POSTGRES_EFFECTIVE_CACHE_SIZE: "3GB"
      # Auto-vacuum settings
      POSTGRES_AUTOVACUUM: "on"
      POSTGRES_AUTOVACUUM_NAPTIME: "1h"
      POSTGRES_LOG_AUTOVACUUM_MIN_DURATION: "250ms"
      POSTGRES_AUTOVACUUM_MAX_WORKERS: "3"
      POSTGRES_AUTOVACUUM_VACUUM_SCALE_FACTOR: "0.1"
      POSTGRES_AUTOVACUUM_ANALYZE_SCALE_FACTOR: "0.05"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount a custom PostgreSQL configuration file
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          memory: 4GB
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yourusername -d time_management_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 25
    # command: >
    #   gunicorn -w 25 -k uvicorn.workers.UvicornWorker
    #   --access-logfile -
    #   --access-logformat '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" Time:%(L)s'
    #   --log-level info
    #   app.main:app --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    
volumes:
  postgres_data: