services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-yourusername}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yourpassword}
      POSTGRES_DB: time_management_db
      # PostgreSQL memory optimization parameters
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # Simplified configuration for now to troubleshoot connection issues
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Changed from 5434 to 5432 to avoid confusion
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-yourusername} -d time_management_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    # Make sure the database accepts connections from other containers
    command: postgres -c listen_addresses='*'

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    
volumes:
  postgres_data: